refactor: data 필드의 dto 클래스 통합
woowacourse-teams/2022-kkogkkog pull request #110
Opened 2022-07-25 06:54 UTC by bugoverdose

## 작업 내용

- data 필드만 지닌 `SuccessResponse<T>` DTO 클래스 구현
  - MyCouponsResponse 클래스 제거 및 대체
  - CouponCreateResponse 클래스 제거 및 대체
  - MembersResponse 클래스 제거 및 대체
  
## 공유사항

- `SuccessResponse<List<K>>`와 같은 형식을 지니는 DTO들만 다시 별도의 DTO 클래스로 분리하고 싶은데, 아직 개수가 너무 적어서 일단은 보류했습니다. 
- 모든 API들이 `{data: ~ }` 형식으로 지니도록 수정하는게 맞지 않나?라는 의문이 들었습니다. 

Resolves #108

2022-07-25 07:00 UTC, bugoverdose reviewed
공통 DTO 명칭을 `SuccessResponse`로 해놨는데 더 적절한 이름이 있을까 싶네요.
원래는 `DataResponse`라고 할려고 했는데, 명칭에 data, info 등은 포함시키지 않고 싶어서 "성공한 응답"이라고 했습니다.

2022-07-25 10:42 UTC, Hyunta requested changes
아직 API가 많지 않아서 오히려 복잡해보이긴 하는데, API가 늘어나면 관리하기 편할 것 같습니다.
SuccessResponse 이름이 아쉽긴 한데 더 나은 이름이 생각나지 않네요...ㅠ

2022-07-25 10:42 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/SuccessResponse.java
>  }
리뷰어의 편의를 위해서 클래스를 새로 만들 때 기존 클래스를 재활용하지 말고 삭제 하고 새로 만들면 좋을 것 같습니다.
MyCouponsResponse -> SuccessResponse 가 되어버려서 MyCouponsResponse가 사라졌다는걸 파악하는데 시간이 걸렸습니다.

2022-07-25 10:42 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/CouponController.java
> +        SuccessResponse<CouponsResponse> myCouponsResponse = new SuccessResponse<>(new CouponsResponse(
이름이 변경되면서 표현이 모호해진 것 같아요
`CouponResponse`는 단일 조회라면
`CouponsResponse`는 복수 조회일 것 같은 느낌인데,
지금은 `CouponsResponse`가 받은 쿠폰과 보낸 쿠폰의 조회라서 

기존 처럼 `MyCouponsResponse`로 유지하는게 좋아보입니다.

2022-07-25 13:02 UTC, Wishoon commented on backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
> +        return new SuccessResponse<>(response.body().jsonPath().getList("data", CouponResponse.class));
흠 이건 좀 치명적이긴 하네요 😭 한번 다른 방안이 있는지 확인이 필요해보입니다

2022-07-25 13:11 UTC, Wishoon requested changes
저도 예전에 시도해봤던 방법이라 좋다고 생각합니다😁😁 다만 인수테스트에서 `as`를 사용하지 못하는 치명적인 문제가 있네요... 이건 한번 논의가 필요할 것 같습니다 😆

2022-07-25 23:56 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/SuccessResponse.java
>  }
삭제하고 새로 만드는건 말이 안됩니다. 새로운 클래스를 구현하여 커밋하고, 기존 클래스들을 순차적으로 대체하라는거겠죠?

이미 그렇게 했습니다. 리뷰할 때는 최종적인 결과물만 보지 말고 우선 커밋 내역을 확인해주시기바랍니다. 

리뷰어 편의를 위해 할 수있는건 이미 다 했다고 생각합니다.

2022-07-26 07:20 UTC, Hyunta approved these changes
고생했습니다 정👍🏻

2022-07-26 07:21 UTC, Wishoon approved these changes

2022-07-26 07:52 UTC, DWL21 approved these changes
정 수고하셨습니다~

2022-07-26 07:54 UTC, merged