feat : 쿠폰 사용 완료 API 구현
woowacourse-teams/2022-kkogkkog pull request #111
Opened 2022-07-25 08:11 UTC by DWL21

## 작업 내용

- 보낸 사람(Sender)과 받은 사람(Receiver)이 쿠폰 사용을 완료하는 기능 구현

## 공유사항

- CouponTest는 보낸 사람과 받은 사람 모든 경우 구현
- CouponTest 구현하다 어느정도 테스트 해야될까 아서와 이야기했습니다. 그래서 CouponServiceTest는 보낸 사람일 경우의 테스트만 구현해 봤습니다. 의견 남겨주시면 감사하겠습니다.

Resolves #109

2022-07-25 09:56 UTC, Hyunta requested changes
고생했습니다 레오!
아까 같이 나눴던 이야기들을 정리해봤습니다.
테스트 커버리지에 대한 회의가 필요할 것 같네요.

2022-07-25 09:56 UTC, Hyunta commented on backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
> +        }
보낸 쿠폰과 받은 쿠폰을 구분지어 확인할 필요가 있는지 의문입니다. 테스트 구조를 그대로 가져가다보니 발생한 문제라고 생각하는데 사용완료기능은 보낸 사람과 받은 사람에 종속적인 기능이 아니라서 인수테스트에 추가된 8개의 테스트가 너무 과하다는 생각입니다.

팀끼리 인수테스트에서 얼마나 세부적인 것까지 다룰지 논의가 필요해보입니다.

2022-07-26 03:22 UTC, bugoverdose requested changes
몇 가지 커멘트 남겼습니다.

2022-07-26 03:22 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponEvent.java
> +    }
제3자가 요청을 보내는 경우에 대한 방어로직이 필요합니다.

```suggestion
    private static void canFinish(boolean isSender, boolean isReceiver) {
        if (!isSender && !isReceiver) {
            throw new ForbiddenException("쿠폰을 보낸 사람과 받은 사람만 사용 완료 처리할 수 있습니다.");
        }
    }
```

2022-07-26 03:22 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponEventTest.java
> +        boolean isReceiver = true;
쿠폰을 보내거나 받은 사람이 아니면 사용 완료를 할 수 없다는 테스트도 추가하는게 어떨까요?

2022-07-26 07:30 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java
> +    }
적용했습니다. 현재 Coupon Service는 보낸 사람만 구현되어 있습니다.

2022-07-26 07:32 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
> +        }
넵 애기했던대로 리펙터링 이야기하면 좋겠네요.

2022-07-26 07:32 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/domain/CouponEvent.java
> +    }
감사합니다 추가했습니다!

2022-07-26 07:32 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponEventTest.java
> +        boolean isReceiver = true;
추가했습니다!

2022-07-26 07:34 UTC, Hyunta approved these changes
고생하셨습니다 레오🦁

2022-07-26 07:45 UTC, bugoverdose approved these changes
몇 가지 커멘트 남겼습니다. 마음에 걸리는 요소가 조금 있지만, 일단 어프루브하고 향후 테스트 코드에 대해 전반적으로 리팩토링 방향에 대해 논의하는 것도 좋을 것 같습니다.

2022-07-26 07:45 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java
> +    }
일단 우테코 스타일로 정렬 명령어 한번 실행하면 좋을 것 같아요.

```suggestion
    private static Stream<Arguments> provideSenderAndReceiver() {
        return Stream.of(
            Arguments.of(MemberFixture.ROOKIE, MemberFixture.ARTHUR, MemberFixture.ROOKIE),
            Arguments.of(MemberFixture.ROOKIE, MemberFixture.ARTHUR, MemberFixture.ARTHUR)
        );
    }
```

2022-07-26 07:45 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java
> +    }
requester가 어떠한 상황에서는 sender가 되고, 어떠한 상황에서는 receiver가 된다는 점이 다소 난해합니다. `@ParameterizedTest`를 사용한다면 `READY`, `REQUESTED`, `ACCEPTED` 등의 상태를 받도록 하는게 테스트 개수도 더 줄고, 가독성이 더 높을 것 같습니다.

2022-07-26 07:47 UTC, Wishoon approved these changes

2022-07-26 07:48 UTC, merged