feat: 쿠폰 사용 요청 및 조회시 날짜를 추가하는 기능
woowacourse-teams/2022-kkogkkog pull request #129
Opened 2022-07-28 04:58 UTC by Wishoon

## 작업 내용

- 쿠폰 사용 요청 시 날짜를 입력받는 기능

  - REQUEST 이벤트 api 분리
  - 해당 API에서만 날짜를 입력받도록 변경

- 쿠폰 조회 시 쿠폰 사용 날짜를 조회하는 기능
  - 단일 조회, 전체 조회에서 쿠폰 사용 날짜를 조회하도록 변경

## 공유사항

일단 기능만 구현한 상태고 내일 전체 리팩토링 과정에서 변경될 내용입니다~!

Resolves #128

2022-07-28 05:30 UTC, bugoverdose approved these changes
고민이 많아지네요.

2022-07-28 05:30 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/CouponRequestEventRequest.java
> +    private LocalDate meetingDate;
```suggestion
    @NotBlank(message = "~")
    private String couponEvent;
    
    @NotNull(message = "~")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate meetingDate;
```

2022-07-28 05:30 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/CouponEventRequest.java
> +import org.springframework.format.annotation.DateTimeFormat;
```suggestion
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
```

2022-07-28 05:30 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/application/CouponServiceTest.java
>              void success_request() {
문구를 전반적으로 이런 느낌으로 수정하는게 가독성이 높지 않나 싶어요.

```suggestion
            @DisplayName("받은 사람이 REQUEST 이벤트와 약속날짜를 보내면, 쿠폰을 REQUESTED 상태로 변경한다.")
            void success_request() {
```

2022-07-28 05:30 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/acceptance/CouponAcceptanceTest.java
>  import java.util.List;
잘 안 보이기는 하는데, 안쓰이지 않나요?

```suggestion
import java.util.List;
```

2022-07-28 05:30 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/application/CouponService.java
> +            coupon.updateMeetingDate(couponChangeStatusRequest.getMeetingDate());
`updateMeetingDate(couponChangeStatusRequest.getMeetingDate())` 호출했을 때 메서드 내부에서 null 검증도 이루어지면 되지 않나 싶어요.

meetingDate를 null로 변경하는 메서드와 null이 아닌 LocalDate를 할당하는 로직 두개로 구분하는 것도 가능한 방법이고요.

2022-07-28 05:30 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponResponse.java
> +    private LocalDate meetingDate;
혹시 이렇게 수정가능한가요?

```suggestion
    @JsonFormat(shape = Shape.STRING, pattern = "yyyy-mm-dd")
    private LocalDate meetingDate;
```

2022-07-28 05:30 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/config/InterceptorConfig.java
> +            .addPathPatterns("/api/coupons/*/event/*");
이 부분 볼 때마다 느끼는건데 차라리 세미콜론을 아랫줄로 옮기는건 어떨까 싶네요.
 
```suggestion
            .addPathPatterns("/api/coupons/*/event")
            .addPathPatterns("/api/coupons/*/event/*")
            ;
```

2022-07-28 05:30 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
> +    private LocalDate meetingDate;
슬슬 실제 MySQL DB에서 제대로 돌아가는지 테스트를 해봐야 할 것 같네요.

2022-07-28 07:27 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponResponse.java
> +    private LocalDate meetingDate;
이렇게 수정하면 `분`이 들어갑니다

2022-07-28 11:08 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/application/dto/CouponResponse.java
> +    private LocalDate meetingDate;
어지럽네요

2022-07-28 13:50 UTC, Wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/CouponRequestEventRequest.java
> +    private LocalDate meetingDate;
수정해서 반영할게용~!

2022-07-28 19:14 UTC, DWL21 requested changes
루키 아서 빠른 시간내에 깔끔하게 잘 구현하셨네요. 리팩터링 전 추가해야할 기능이 있으니 확인 부탁드립니다.

2022-07-28 19:14 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/CouponController.java
> +    }
사용요청을 분리하니 좋네요. 컨트롤러에서는 분리된 것 같은데 서비스에서는 메서드 하나로 처리해 분기문이 필요한 것 같네요. 혹시 서비스에서도 역할을 분리하는건 어떤가요??

2022-07-28 19:14 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/dto/CouponRequestEventRequest.java
> +import javax.validation.constraints.NotEmpty;
사용되지 않는 것으로 보이네요.

2022-07-28 19:14 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
> +    }
예약 날짜가 현재 날짜 이전인지 검사하는 부분이 없는 것 같습니다. 과거 날짜로는 약속을 잡을 수 없게 해야할 것 같은데 어떻게 생각하시나요??

2022-07-28 19:14 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/domain/CouponTest.java
> +    }
유효하지 않은 날짜일 경우를 확인하는 테스트가 필요해 보입니다.

2022-07-29 01:29 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/application/CouponService.java
> +            coupon.updateMeetingDate(couponChangeStatusRequest.getMeetingDate());
현재 REQUEST 이벤트를 받을 때만 meetindDate가 필요하다고 논의가 되어서, changeStatus가 분리될 가능성이 높다고 생각했습니다. 추후 분리할 때를 고려해서 일단 Service에서 체크를 하고 있습니다.

2022-07-29 01:31 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/presentation/CouponController.java
> +    }
추후 Service의 changeStatus에서 request를 따로 handling할 때 dto를 나누면 좋을 것 같아요. 우선 지금은 그렇게하면 테스트 코드에서 request 부분이 전부 깨져서 이렇게 구현했습니다.

2022-07-29 01:31 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
> +    }
그러게요 나중에 구현해야할 사항이라고 생각합니다.

2022-07-31 17:02 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
> +    }
과거 날짜로는 약속을 잡을 수 없기 때문에 이 부분은 나중이 아닌 기능 구현 시 추가가 필요한 부분이라고 생각됩니다.

2022-07-31 17:12 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/domain/Coupon.java
> +    }
유효하지 않은 날짜에 대한 방어 로직은 필요할 것 같은데 아서의 생각은 어떤지 궁금하네요.

2022-08-01 07:29 UTC, DWL21 approved these changes

2022-08-01 07:46 UTC, merged