feat: Slack 통합 알림봇 사용
woowacourse-teams/2022-kkogkkog pull request #312
Opened 2022-09-08 05:24 UTC by DWL21

## 작업 내용

- woowacourse 통합 알림 봇 서버로 요청을 보내는 클래스를 구현한다.
  - request url, jwt token을 환경변수로 받는다.
  - 워크스페이스에 봇 토큰이 없으면 해당 클래스로 알림 전송 요청을 보낸다.

- SlackClient에서 알림 전송 기능을 분리한다.

- PushAlarmClient 인터페이스를 구현해 일반적인 전송과 woowacourse 워크스페이스 전송 과정을 추상화한다.

## 공유사항

비즈니스 로직을 건드리지 않게 infrastructure 패키지만 변경하였습니다. PushAlarmEvent 클래스에서 woowacourse 워크스페이스 식별이 불가능한 문제가 있습니다. 그러므로 봇 토큰이 없는 경우만 확인하여 없는 경우 woowacourse 통합 서버로 알림 전송을 요청합니다.

Resolves #308

2022-09-08 05:29 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +                            message))))
indent가 5개네요

2022-09-08 05:36 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +        }
푸쉬 알람 전송 후 그 성공 여부를 응답으로 받아야 하는지 의문이 들어요

2022-09-08 05:36 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +                            message))))
indent가 5개네요

2022-09-08 05:36 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListenerTest.java
> +    @MockBean
```suggestion
    CommonPushAlarmClient pushAlarmClient;
    @MockBean
```

2022-09-08 05:36 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
> +        woowacoursePushAlarmClient.requestPushAlarm(accessToken, hostMemberId, message);
우테코 사람인 경우에 우테코 푸시알람을 보내고, 그게 아니면 botAccessToken을 확인하고 있는 경우 푸시알람을 보내도록 해야하지 않나요?

2022-09-08 05:55 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListenerTest.java
> +    @MockBean
수정했습니다~

2022-09-08 05:57 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +                            message))))
확실히 복잡하네요. 메서드 분리해봤는데 이건 어떤가요? [refactor: 통합 알림 봇 요청 메서드 분리](https://github.com/woowacourse-teams/2022-kkogkkog/pull/312/commits/83bb80887f49dd4b7f6dbac6dfe0db42540b9c09)

2022-09-08 05:59 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +        }
상태코드를 확인하여 4xx or 5xx 이면 예외를 발생시키고 로그를 찍게 수정하였습니다.

2022-09-08 06:07 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
> +        woowacoursePushAlarmClient.requestPushAlarm(accessToken, hostMemberId, message);
지금 우테코 사람인지 식별하려면 workspace id가 woowacourse인 TFELTJB7V인지 확인해야 되더라고요. 현재는 woowacourse 워크스페이스에는 봇 토큰이 없으니 슬랙 서버로 요청을 보낼려고 했습니다. 변경하려는데 혹시 우테코 사람을 식별하는 다른 방법이 있을까요?

2022-09-08 06:13 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
> +        woowacoursePushAlarmClient.requestPushAlarm(accessToken, hostMemberId, message);
오 쉽게 수정가능하네요. 변경해보겠습니다.

2022-09-08 06:37 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
> +        woowacoursePushAlarmClient.requestPushAlarm(accessToken, hostMemberId, message);
[refactor: woowacourse 워크스페이스일 경우 알림을 보내게 변경](https://github.com/woowacourse-teams/2022-kkogkkog/pull/312/commits/da34623ccb616b111cb052c9a15e4e3007f86391)

2022-09-08 06:42 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +        }
성공할 경우에는 아무 작업도 하지 않지만 실패할 경우에는 서버로그로 어떤 이유로 실패했는지 확인하려는 목적이었는데 어떻게 생각하시나요??  https://github.com/slack-integrated-bot/slack-integration-bot/blob/main/docs/api.md

2022-09-09 05:08 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListenerTest.java
> +    WoowacoursePushAlarmClient woowacoursePushAlarmClient;
이 필드들 앞에 private이 없는 이유가 있나요?

2022-09-09 05:08 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListenerTest.java
>          private ReservationSaveRequest reservationSaveRequest;
`@BeforeEach`로 초기화되는 workspace, sender, receiver는 필드여도 괜찮은데, 왜 coupon, reservation 등 테스드 메서드 내에서 별도로 생성하는 값들까지 인스턴스 필드에 재할당하나요?

2022-09-09 05:24 UTC, bugoverdose requested changes
전반적인 수정 부탁드립니다.

2022-09-09 05:24 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/CommonPushAlarmClient.java
> +    private final WebClient messageClient;
전반적인 코드 정렬 부탁드립니다.

2022-09-09 05:24 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +    }
Q1. 왜 매개변수가 저렇게 정렬되어있는건가요
Q2. 왜 굳이 PushAlarmClient가 두가지 객체로 구분되는건가요? 다형성의 이점을 살리고 있는 부분이 있나요?

2022-09-09 05:24 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmClient.java
> +    }
왜 디폴트 메서드를 사용한건가요? 왜 인터페이스여야 하나요?

2022-09-09 05:24 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
>      }
현재 Member 테이블의 워크스페이스 정보가 woowacourse에 해당된다는 점을 어떻게 알 수 있나요? 
우테코 워크스페이스 사용자인지를 파악하려면 email을 사용해야 하지 않나요?

알림 두번 보내지 않도록 return해줘야 할 것 같고, 이상한 위치에 공백이 있어요.

```suggestion
        if (pushAlarmEvent.isWoowacourseWorkspace()) {
            woowacoursePushAlarmClient.requestPushAlarm(accessToken, hostMemberId, message);
            return;
        }
        if (pushAlarmEvent.hasBotAccessToken()) {
            commonPushAlarmClient.requestPushAlarm(accessToken, hostMemberId, message);
        }
    }
```

2022-09-09 05:40 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
>      }
아니면 woowacourse 워크스페이스의 사용자는 무조건 해당 워크스페이스의 정보만을 사용하도록 로그인 쪽 로직을 수정해야 할 것 같아요.

2022-09-09 05:47 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/event/PushAlarmEvent.java
> +    private static final String WOOWACOURSE_WORKSPACE_ID = "TFELTJB7V";
TEAM ID, USER ID 값들을 테스트와 프로덕션 코드에 하드코딩하지 않고 개발해보면 어떨까요? 
PushAlarmClient 빈에서 yml의 값을 주입받도록 하는 등의 방법이 있습니다.

2022-09-09 23:45 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
>      }
> 우테코 워크스페이스 사용자인지를 파악하려면 우테코 크루의 email 목록과 사용자의 이메일 값을 비교해야 하지 않나요?
현재는 다른 워크스페이스 계정으로 로그인하면 해당 워크스페이스로 알림을 보냅니다. 정 피드백을 들어보니 리팩터링이 필요할 것 같네요.
1. 우선 email로 woowacourse 워크스페이스 사용자를 확인하여 메세지를 보낸다. 이후 다른 워크스페이스인지 확인한다.
2. woowacourse 이외의 워크스페이스로는 알림을 보내지 않는다.

제 생각은 1번은 적용하는게 좋을 것 같고 2번은 확장성이 제한된다는 단점이 있을 것 같은데 어떻게 생각하시나요??

2022-09-09 23:50 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +    }
매개변수는 SlackClient의 순서를 따랐습니다.

2022-09-09 23:51 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/event/PushAlarmEvent.java
> +    private static final String WOOWACOURSE_WORKSPACE_ID = "TFELTJB7V";
이메일로 현재 목록을 받아와 woowacourse인지 확인하게 되면 해당 부분은 사라지네요.

2022-09-09 23:52 UTC, DWL21 commented
정 연휴에도 리뷰 남기시느라 수고 많으셨습니다! 나머지 부분은 https://github.com/woowacourse-teams/2022-kkogkkog/pull/312#discussion_r967543195 이 결정되면 리팩터링하면서 질문하고 반영하겠습니다~

2022-09-10 00:28 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
>      }
추가로 Member 부분을 보면서 알게 된 건데 지금 구현한건 최초에 우아코스로 가입하지 않으면 안되네요ㅜ

2022-09-10 00:31 UTC, DWL21 commented
정 연휴 보내고 천천히 리뷰주셔요!

2022-09-10 21:10 UTC, Wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +        }
응답 성공과 실패 여부 정도는 로그로 남기는 건 괜찮지 않을까요?? 아무 확인도 하지 않는다면 문제 상황이 생기는지 모니터링이 힘들거라 생각해서 로그는 괜찮다는 의견입니다!!

2022-09-10 21:11 UTC, Wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
> +        woowacoursePushAlarmClient.requestPushAlarm(accessToken, hostMemberId, message);
굿굿 👍

2022-09-10 21:25 UTC, Wishoon requested changes
레오!! 통합 알림봇 코드 구현 잘봤습니다!! 제 생각에는 다형성 처리와 워크스페이스 사용자 관련 부분을 제외하고는 문제 없어보입니다!! 추가적으로 통합 알림봇이 테스트 하기가 어려워서 실제 배포하면 문제가 생길 수도 있어요 ㅠㅠ 나중에 같이 확인해보시죠 💪

2022-09-10 21:25 UTC, Wishoon commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListenerTest.java
>          private ReservationSaveRequest reservationSaveRequest;
위의 코멘트 처럼 WorkSpace 필드가 필요 없는 부분은 제거해서 사용해도 괜찮을 것 같아요~~

2022-09-10 21:25 UTC, Wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/PushAlarmListener.java
> +    private final WoowacoursePushAlarmClient woowacoursePushAlarmClient;
이렇게 두개의 구체 클래스로 필드를 가져가는 것보다는 전략으로 가져갈 수도 있을 것 같아요 ㅎㅎ 시간이 되면 수정해주시고 아니면 다음 리팩토링 요소로 남겨도 좋습니다!

2022-09-10 21:25 UTC, Wishoon commented on backend/src/main/resources/application.yml
> +
👍

2022-09-10 21:25 UTC, Wishoon commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/CommonPushAlarmClientTest.java
> +        + "}";
통합 봇 개발을 할 때 이슈사항으로 형식이 안맞으면 문제가 생기더라고요!! 지금은 text라서 크게 문제될 건 없어보이는데 추후 block, attatchment 사용시 문제가 생길 수도 있으니 나중에 적용한다면 `slack block` 생성 프로그램을 활용해서 만들어주세요 ㅎㅎ

2022-09-10 21:25 UTC, Wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +    }
호오.. mono 사용시 에러 처리 스팩을 `Mono.error`를 통해서 처리해야 하는건가요?? (몰라서..)

2022-09-13 04:37 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +    }
상태코드를 받아 처리하려면 이런 방법이 있더라고요 ㅎㅎ 여러 방법이 있습니다.

2022-09-13 04:37 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClient.java
> +    }
그때 시도해본 것 중에 에러 안난 코드가 이거였어요😅

2022-09-13 07:12 UTC, closed without merging