feat: 구글로 로그인했을 경우 기존 회원과 통합할 수 있도록 구현
woowacourse-teams/2022-kkogkkog pull request #415
Opened 2022-10-04 10:04 UTC by Hyunta

## 작업 내용

구글로 로그인했을 경우 2가지 경우가 있습니다.
1. 기존에 가입된 구글 or 슬랙 회원이 있는 경우
  - member의 Id 값을 받아와서 토큰으로 만들어 반환한다.
2. 신규 회원인 경우
  - accessToken과 isNew=true를 반환한다.
  - 닉네임과 accessToken을 받아 signUp/google로 요청이 온다.
  - 새로운 member를 생성한다(userId, workSpaceId는 null 이다.)
  - member의 Id값을 받아와서 토큰으로 만들어 반환한다.

회원가입된 회원이 구글로 로그인하는 경우 일어나는 일은 조회 후 memberId를 읽어오는 과정만 있습니다.
문제가 될 수도 있다고 판단된 부분은 구글로 회원가입한 사용자가 다시 Slack으로 로그인 하는 경우입니다.

<구글로 회원가입한 사용자가 Slack으로 로그인하는 Flow>
1. SlackUserInfo에서 중복되는 이메일이 존재하므로 memberService의 update를 실행합니다.
2. workspaceUserRepository에는 userId와 동일한 회원이 존재하지 않습니다.
3. memberRepository에 findByEmail을 하면 구글로 가입했던 Member가 반환됩니다.
4. integrateNewWorkSpaceUser 메서드에서 현재 로그인한 Slack 계정을 기반으로 userId, imageUrl, workspace를 받아옵니다.

위 flow대로 흘러가면 문제가 없다고 판단되어서 우선 제출합니다. 혹시 이상한점 있으면 커멘트로 남겨주세요.

## 공유사항

merge된 이후 pushAlarm 부분도 고려해보겠습니다.

Resolves #392

2022-10-05 04:12 UTC, wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/auth/presentation/AuthV2Controller.java
> +        MemberCreateResponse memberCreateResponse = authService.loginByMemberId(id);
이전의 로그인 로직과 동일하게 구현해서 다음과 같은 로직이 작성된 것 같은데 AuthService에서 MemberService를 조회하는 식으로 변경하는 건 어떨까요?? (지금은 그대로 두고 나중에 변경)

2022-10-07 06:39 UTC, bugoverdose commented on backend/src/main/resources/db/migration/V2.3__make_user_id_nullable.sql
> +    MODIFY COLUMN `user_id` VARCHAR(255);
`workspace_id`도 nullable해야하지 않나요?

```suggestion
ALTER TABLE `member`
    MODIFY COLUMN `user_id` VARCHAR(255);
ALTER TABLE `member`
    MODIFY COLUMN `workspace_id` VARCHAR(255);    
```

2022-10-07 06:39 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
> +        String email = userInfo.getEmail();
슬랙 OAuth 때도 느낀 점이지만 특별한 이유가 없다면 클래스명이 굳이 ~Info, ~Data로 끝날 이유는 없다고 생각해요. 
데이터를 전달한다는 취지를 강조하고자 한다면 ~Dto라고 하는건 어떨까요?

```suggestion
    public Long save(GoogleUser userInfo, String nickname) {
        String email = userInfo.getEmail();
```

2022-10-07 06:39 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
> +    }
👍
이렇게 하고 서비스의 save 로직을 한줄로 묶는건 어떨까요?
```suggestion
    public Member(String nickname, String email, String imageUrl) {
        this(null, null, null, new Nickname(nickname), email, imageUrl);
    }
```

2022-10-07 06:39 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
> +        );
```suggestion
        Member savedMember = memberRepository.save(new Member(nickname, email, imageUrl));
```

2022-10-07 07:10 UTC, Hyunta commented on backend/src/main/resources/db/migration/V2.3__make_user_id_nullable.sql
> +    MODIFY COLUMN `user_id` VARCHAR(255);
클래스에서는 (default)nullable=true로 되어있어서 인지를 못했네요, 반영하겠습니다!

2022-10-07 07:28 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
> +        String email = userInfo.getEmail();
저도 정의 의견에 어느정도 동의합니다. userInfo는 oauth 규약도 아니고 하는 역할도 dto와 비슷한 수준이라고 생각해서 `GoogleUserDto` 정도로 가는것도 일리있다고 생각합니다.

가능할지 모르겠지만, 만약 추상화를 진행하게 된다면 Dto라는 이름보다는 적절한 이름이 필요하지 않을까요?

2022-10-07 07:30 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
> +    }
변경했습니다

2022-10-07 07:31 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
> +        String email = userInfo.getEmail();
추상화가 적절할지는 코드를 봐야 알 것 같은데, 
함께 묶는다면 OAuthUser를 상위타입으로 하고, SlackUser, GoogleUser라는 구현체를 만드는건 어떨까요?

2022-10-07 07:42 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/auth/presentation/AuthV2Controller.java
> +        @RequestBody InstallSlackAppRequest installSlackAppRequest) {
일단은 파일 정렬 없이 이 부분 원상복구할까요?

2022-10-07 10:33 UTC, wishoon approved these changes
굿 👍 위에 올라와 있는 피드백 반영후 머지하면 될 것 같습니다

2022-10-07 10:33 UTC, wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
> +        String email = userInfo.getEmail();
저도 이름만 적절하게 통일된다면 어떤 명칭을 사용하든 문제는 없다고 생각해요!

2022-10-07 11:51 UTC, DWL21 reviewed
아서 안녕하세요! 코드 상 문제 없어보이네요. 다만 구글만 가입한 사람은 알림 확인이 필요해보입니다! 고생하셨습니다!

2022-10-07 11:51 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
> +    public Member(String nickname, String email, String imageUrl) {
다른 엔티티처럼 주 생성자를 앞에 하는건 어떤가요?

2022-10-07 11:51 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/auth/application/AuthServiceTest.java
> +
```suggestion
```

2022-10-07 11:51 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
>      public Member(String userId, Workspace workspace, Nickname nickname, String email,
근데 userId와 workspace가 null이면 알림 쪽에서 문제가 생길 수 있어 확인이 필요해 보입니다.

2022-10-07 11:53 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
>      public Member(String userId, Workspace workspace, Nickname nickname, String email,
집가서 확인해보겠습니다.

2022-10-07 11:58 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
>      public Member(String userId, Workspace workspace, Nickname nickname, String email,
알람쪽은 다음 PR에서 완성해서 올릴게요

2022-10-07 12:04 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
> +    public Member(String nickname, String email, String imageUrl) {
저는 주 생성자가 뒤에 있는걸 선호하긴 합니다. 취향 차이라고 생각하고 minor한 이슈이긴 하지만 로직 메서드와 분리할 수 있어서요.
그리고 Coupon을 제외하고 WorkSpaceUser, Member 에만 생성자가 있는 것 같은데 둘다 주 생성자가 맨 아래 있습니다

2022-10-07 12:12 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/member/application/MemberService.java
> +        String email = userInfo.getEmail();
GoogleUser는 마치 저희 Member인것 처럼 보일 수 있어서 일단 GoogleUserDto로 변경하겠습니다

2022-10-07 12:46 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
>      public Member(String userId, Workspace workspace, Nickname nickname, String email,
기존 알림은 accessToken이 null이면 보내지 않아 괜찮네요. 우선 구글로만 로그인 한 경우 우테코 봇에서 알림을 보내지 않는 경우를 추가하면 될 것 같습니다. WoowacoursePushAlarmEvent 의 shouldNotSendPushAlarm 메서드에 hostMemberId == null 조건을 추가하면 되겠네요.

2022-10-07 12:57 UTC, DWL21 requested changes
현재 상태에서 머지하면 구글로만 회원가입한 사람은 userId가 null이네요. userId이 null이면 우테코 알림을 시도하므로 실패로그가 계속 남을 것 같아 보입니다. 우선 알림쪽 구현 전까지 우테코 봇 이벤트 객체shouldNotSendPushAlarm 메서드에 hostMemberId == null 인 조건을 추가해 userId이 null이면 우테코 알림을 요청하지 않는다로 바꿔 방어할 수 있어요.

2022-10-07 12:59 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/member/domain/Member.java
>      public Member(String userId, Workspace workspace, Nickname nickname, String email,
```java
WoowacoursePushAlarmEvent.java

public boolean shouldNotSendPushAlarm() {
        return hostMemberId == null || couponEvent == CouponEventType.FINISH;
    }

```

2022-10-11 04:55 UTC, DWL21 approved these changes
현재 구글 유저 실서비스 하지 않아 일단 머지하기로 협의함

2022-10-11 05:17 UTC, merged