feat: 미등록 쿠폰 기능 구현
woowacourse-teams/2022-kkogkkog pull request #417
Opened 2022-10-05 07:06 UTC by DWL21

## 작업 내용
- 모든 기능에 대해 Restdocs 작성 완료

- 미등록 쿠폰 기능 구현
  - 미등록 쿠폰 생성
  - 쿠폰코드로 쿠폰 등록
    -  발급되거나 만료된 쿠폰을 해당하는 상태로 변경
  - 쿠폰코드로 쿠폰 조회
  - 나의 미등록 쿠폰 조회
    - 미등록 쿠폰 상태를 반환
  - 미등록 쿠폰 아이디로 내 미등록 쿠폰 단일 조회
  - 미등록 쿠폰 삭제

## 공유사항
- 구현 예정 -> 추가 기능이라 PR을 분리하려고 합니다.
  - 나의 미등록 쿠폰 조회에서 쿠폰이 등록되었을 경우 받은 사람을 반환하는 기능
  - 쿠폰 발급 기록
  - 쿠폰 발급 푸시 알림

Resolves #347

2022-10-06 06:49 UTC, Hyunta requested changes
큰 기능인데 혼자하시느라 고생하셨습니다 레오!
보시고 이상한 부분있으면 알려주세요
테스트코드도 꼼꼼히 잘 짜주셨네요👍🏻
전반적으로 삭제 로직이 상태 변경이 아닌가 싶어서 관련해서 리뷰 남겼습니다!

2022-10-06 06:49 UTC, Hyunta commented on backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/UnRegisteredCouponServiceTest.java
> +    class Delete {
delete라는 표현이 적합한지 잘 모르겠습니다. 이 부분에 관해서 백엔드끼리 논의가 필요할 것 같은데 저는 이 로직이 삭제랑 관련이 없다고 생각합니다.

ISSUED -> REGISTERED or EXPIRED 로 상태가 변하는거 아닌가요?

coupon에서 상태변경을 만든것처럼 구현하는건 어떤가요?

2022-10-06 06:49 UTC, Hyunta commented on backend/src/test/java/com/woowacourse/kkogkkog/coupon/domain/UnRegisteredCouponTest.java
> +}
어떤 테스트를 하려는건지 테스트의 목적이 명확하지 않아요.
`CouponFixture.getUnregisteredCoupon()` 이 메서드를 없애고 `UnregisteredCoupon.of()`를 바로 호출합시다

2022-10-06 06:49 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/UnregisteredCouponService.java
> +    public List<UnregisteredCouponResponse> findAllBySender(Long memberId) {
```suggestion
    @Transactional(readOnly = true)
    public List<UnregisteredCouponResponse> findAllBySender(Long memberId) {
```

2022-10-06 06:49 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/UnregisteredCouponService.java
> +        }
memberRepository에 조회할 필요없이 받아온 unregisteredCoupon에서 값 비교만 해줘도 될 것 같습니다.

2022-10-06 06:49 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/UnregisteredCouponService.java
> +        }
이 영역은 UnregisteredCoupon이 갖고 있도록 하는건 어떤가요?
최대값, 최솟값에 대한 정책도 내부로 가져갈 수 있어서 좋아보입니다

2022-10-06 07:14 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/UnRegisteredCouponServiceTest.java
> +        void fail_quantity_excess() {
상수를 실수로 바꾸면 테스트가 실패해 확인할 수 있게 하기위해 테스트 코드는 하드코딩하는 것을 선호해요.

2022-10-06 07:20 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/UnRegisteredCouponServiceTest.java
> +    class Delete {
미등록 쿠폰 삭제는 상태 변경과 다르게 미등록 쿠폰 자체를 없애는 기능을 제공해요. 나의 쿠폰 조회나 단일 쿠폰 상세 조회도 불가능해요. 그러므로 상태 변경시에 쿠폰과 다르게 취급하는게 논리적으로 맞다고 생각하여 논리적 삭제로 구현하였습니다.

2022-10-06 07:22 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/coupon/application/UnRegisteredCouponServiceTest.java
> +        void fail_quantity_excess() {
cansave가 validate로 엔티티에 내려갔어요. 서비스 레이어는 허용여부를 검사하고, 엔티티는 지금처럼 최대 최소를 상세히 검사하는 건 어떤가요?

2022-10-06 07:35 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/coupon/domain/UnRegisteredCouponTest.java
> +}
getUnregisteredCoupon 이 UnregisteredCoupon.of()을 호출하고 있어 달라지는 건 없는 것 같아요. 오히려 Coupon과 달리 예외 케이스가 없으니 해당 테스트는 필요 없다고 생각하시나요?

2022-10-06 07:37 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/UnregisteredCouponService.java
> +        }
변경했습니다. Outdated 되었네요.

2022-10-07 06:51 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/UnregisteredCouponSaveRequest.java
> +            CouponType.valueOf(couponType));
스트림 파이프라인으로 쭉 묶을 수 있을 것 같아요.

2022-10-07 06:51 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/CouponController.java
> +                                                @RequestBody String couponCode) {
정렬합시다

2022-10-07 06:51 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/UnregisteredCouponController.java
> +        return ResponseEntity.ok(new UnregisteredCouponsResponse(unregisteredCoupons));
DTO명이 너무 긴데 변수추론을 쓰는게 어떨까요? 파일 위쪽의 import문의 개수도 많이 줄 것 같아요

```suggestion
    public ResponseEntity<UnregisteredCouponsResponse> showAll(@LoginMemberId Long loginMemberId) {
        final var unregisteredCoupons = unregisteredCouponService.findAllBySender(loginMemberId);
        return ResponseEntity.ok(new UnregisteredCouponsResponse(unregisteredCoupons));
```

2022-10-07 06:51 UTC, bugoverdose commented on backend/src/main/resources/db/migration/V3.0__create_unregistered_coupon_table.sql
> +    `id` BIGINT NOT NULL AUTO_INCREMENT
스키마 수정 작업이 있으니 해당 PR의 머지 순서를 신경써야 할 듯 합니다.

2022-10-07 06:51 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/acceptance/UnregisteredCouponAcceptanceTest.java
> +            UnregisteredCouponDetailResponse.class);
👍 클래스명이 너무 긴데, 다른 곳들도 하는건 어떨까요?

```suggestion
        var response = 미등록_쿠폰_생성을_요청하고(senderToken, 미등록_COFFEE_쿠폰_생성_요청(1));
        String couponCode = response.getData().get(0).getCouponCode();

        var extract = 쿠폰코드로_단일_미등록_쿠폰_상세정보를_조회한다(couponCode);

        var actual = extract.as(UnregisteredCouponDetailResponse.class);
```

2022-10-07 06:51 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/support/fixture/dto/UnregisteredCouponDtoFixture.java
> +        return new UnregisteredCouponDetailResponse(
파일 정렬을 적용해봅시다

2022-10-07 07:36 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/UnregisteredCouponController.java
> +        return ResponseEntity.ok(new UnregisteredCouponsResponse(unregisteredCoupons));
좋은 제안인 것 같습니다. 미등록 쿠폰 dto에 한해 var를 사용하려 하는데 다른 분들은 어떻게 생각하시나요? 모두 괜찮으면 적용하겠습니다.

2022-10-07 07:41 UTC, DWL21 commented on backend/src/test/java/com/woowacourse/kkogkkog/support/fixture/dto/UnregisteredCouponDtoFixture.java
> +        return new UnregisteredCouponDetailResponse(
정이랑 확인완료. 스타일 수정 요

2022-10-12 02:28 UTC, Hyunta approved these changes

2022-10-12 03:17 UTC, bugoverdose approved these changes
커멘트 남겼습니다.

2022-10-12 03:17 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/presentation/CouponController.java
> +        CouponResponse couponResponse = couponService.saveByCouponCode(loginMemberId, couponCode);
개인적으로 `UnregisteredCoupon`이라는 도메인명에 맞게 register라는 명칭을 더 활용하면 좋을 듯합니다.

```suggestion
    public ResponseEntity<CouponResponse> registerCouponCode(@LoginMemberId Long loginMemberId,
                                                           @RequestBody String couponCode) {
        CouponResponse couponResponse = couponService.saveByCouponCode(loginMemberId, couponCode);
```

2022-10-12 03:17 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/exception/UnregisteredCouponQuantityExcessException.java
> +    }
"최대 X개의 미등록 쿠폰만 생성할 수 있습니다." 형식은 어떠할까요?

2022-10-12 03:57 UTC, wishoon approved these changes
추가 의견 남겼습니다~

2022-10-12 03:57 UTC, wishoon commented on backend/src/docs/asciidoc/coupon.adoc
> +=== 쿠폰코드로 쿠폰 생성
조금 늦은 의견이거 같은데 미등록 쿠폰과 쿠폰코드가 조금 일치하지 않는거 같아서요 둘의 용어를 통일하는건 어떨까요??

2022-10-12 03:57 UTC, wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/UnregisteredCouponSaveRequest.java
> +    private final Integer quantity;
이부분도 Wrapper를 사용한 이유가 혹시 있을까요?

2022-10-12 03:57 UTC, wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/UnregisteredCoupon.java
> +@SQLDelete(sql = "UPDATE unregistered_coupon c SET c.deleted = true WHERE c.id=?")
변경감지 만으로도 soft delete가 가능할 것 같은데 이렇게 한 이유가 혹시 있을까요??

2022-10-12 04:01 UTC, DWL21 commented on backend/src/docs/asciidoc/coupon.adoc
> +=== 쿠폰코드로 쿠폰 생성
변경하지 않았었네요! 변경하겠습니다.

2022-10-12 04:03 UTC, DWL21 commented on backend/src/docs/asciidoc/coupon.adoc
> +=== 쿠폰코드로 쿠폰 생성
메서드 이름을 그대로 가져다 썼네요. 미등록 쿠폰 수령으로 변경하는 건 어떤가요??

2022-10-12 04:07 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/application/dto/UnregisteredCouponSaveRequest.java
> +    private final Integer quantity;
수량은 프론트에서 바디에 quantity를 넣지 않는경우 0이 아닌 null로 인식하게 하기위해 레퍼 타입을 사용하였습니다.

2022-10-12 04:26 UTC, DWL21 commented on backend/src/main/java/com/woowacourse/kkogkkog/coupon/domain/UnregisteredCoupon.java
> +@SQLDelete(sql = "UPDATE unregistered_coupon c SET c.deleted = true WHERE c.id=?")
SqlDelete 어노테이션을 사용하여 모든 delete에 대해 실제 엔티티 삭제 대신 deleted 컬럼 변경으로 재정의하고자 하였습니다. 서비스에서 삭제 전 더티 체킹도 포함되어 있습니다.

2022-10-12 04:47 UTC, merged