feat: 구글 푸시알람 기능 구현
woowacourse-teams/2022-kkogkkog pull request #457
Opened 2022-10-12 09:19 UTC by Hyunta

## 작업 내용

기본적인 푸시알람 흐름입니다.
1. 가입형태에 상관없이 우테코 이메일이면 우테코 통합봇으로 보냅니다.
2. 구글로만 로그인한 경우 알림을 안보냅니다.
3. 슬랙으로 로그인한 경우 슬랙 알림을 보냅니다.

WoowaCourseUserRepository에서 cache값에 값을 저장하는 기능만 구현되어 있습니다.
나중에 스케쥴러가 도입되면 일정 주기마다 업데이트하는 로직이 필요할 것으로 보입니다.

## 공유사항

eventPublisher에 Test가 필요하게 되어 Mockito를 썼습니다.
과정 중에 equals와 Hashcode 재정의를 했는데, 개선안이 있으면 공유해주세요.

Resolves #392

2022-10-12 09:26 UTC, bugoverdose requested changes
unregisteredCoupon 관련 구현내역이 사라진 것 같아요. 확인바랍니다.

2022-10-12 09:26 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/domain/WoowacourseUserRepository.java
> +    }
일단은 이렇게 하고 스케줄러 도입 후 주기적으로 재갱신합시다

2022-10-12 09:26 UTC, bugoverdose commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/event/PushAlarmPublisher.java
>      }
공백이 살짝 많은 것 같아요.
```suggestion
        if (woowacourseUserRepository.contains(hostMember.getEmail())) {
            String userId = woowacourseUserRepository.get(hostMember.getEmail());
            publisher.publishEvent(WoowacoursePushAlarmEvent.of(userId, couponHistory));
            return;
        }
        if (hostMember.getWorkspace() == null) {
            return;
        }
        publisher.publishEvent(PushAlarmEvent.of(couponHistory));
    }
```

2022-10-12 09:31 UTC, bugoverdose commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClientTest.java
> +                + "}")
줄바꿈이 과하게 많아요. ObjectMapper를 쓰거나 지금 구조에서 공백만 줄여도 될 것 같아요.

2022-10-13 04:20 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/event/PushAlarmPublisher.java
>      }
반영했습니다

2022-10-13 04:21 UTC, Hyunta commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmClientTest.java
> +                + "}")
ObjectMapper를 사용하도록 변경했습니다.

2022-10-13 09:16 UTC, wishoon commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/dto/WoowacourseUserResponse.java
> +    private WoowacourseProfileResponse profile;
오.. 혹시 이렇게 분리한 이유가 있을까요??

2022-10-13 09:16 UTC, wishoon commented on backend/src/test/java/com/woowacourse/kkogkkog/acceptance/support/AcceptanceTestConfig.java
> +public class AcceptanceTestConfig {
테스트 환경에서만 작동한다는 명시가 있어야 할 것 같아요 ㅎㅎ

2022-10-14 12:17 UTC, Hyunta commented on backend/src/test/java/com/woowacourse/kkogkkog/infrastructure/application/WoowacoursePushAlarmListenerTest.java
> +        @RepeatedTest(1000)
앗 지울게요

2022-10-14 12:23 UTC, Hyunta commented on backend/src/main/java/com/woowacourse/kkogkkog/infrastructure/dto/WoowacourseUserResponse.java
> +    private WoowacourseProfileResponse profile;
[통합봇 반환값 명세](https://github.com/slack-integrated-bot/slack-integration-bot/wiki/API-Documentation)가 이렇게 나와있어서 이렇게 구현했습니다.

```
{
  "members": [
    {
      "id": "USLACKBOT",
      "profile": {
        "email": null
      }
    },
    {
      "id": "U03U987DB0W",
      "profile": {
        "email": "heonga2@gmail.com"
      }
    },
    {
      "id": "U03V5H72L1W",
      "profile": {
        "email": "jinyoungchoi95@gmail.com"
      }
    }
  ]
}
```

2022-10-18 01:18 UTC, merged