feat: 쿠폰 생성 페이지의 웹 접근성을 위한 기능 개발
woowacourse-teams/2022-kkogkkog pull request #485
Opened 2022-10-17 14:31 UTC by juunzzi

## 작업 내용

- 키보드만으로 쿠폰 생성을 가능하게 한다.

  - [x] 기존의 focus가 불가능하던 섹션에 대해 `tabIndex=0`를 부여
  - [x] `tabIndex=0`을 부여하여 `focusable`하도록 구현
  - [x] `selectInput`의 `option`을 버튼으로 구성하여 탭 키로 전환, 엔터키로 선택이 가능하도록 구현
  - [x] `FindUserInput` 역시 클릭하면 모달을 띄운다라는 역할에 맞게 `button` 태그로 구성한다.
  - [x] `Modal`은 `role="dialog"`이다.
  - [x] `UserSearchModal` 내부의 옵션들을 버튼 태그로 만들어 탭 키로 전환, 엔터 키로 선택 가능 하도록 구현
  - [x] `UserSearchModal` 내부의 옵션들은 선택 된 것인지 아닌지에 대한 피드백을 사용자에게 전달한다.
  - [ ] `Modal`의 종료 버튼이 있어야한다.

## 공유사항

해당 작업 내용에 관한 부연 설명 및 및 향후 작업해야 할 내용 등에 대한 설명

Resolves #이슈번호

2022-10-17 14:37 UTC, euijinkk commented on frontend/src/@components/coupon/CouponCreateForm/index.tsx
> +            </button>
준찌 이거는 제가 아래와 같이 구현해서 alt 다 바꾸어뒀는데요.
아래처럼하는거 어때용? 
couponTypeCollection 없이 img를 렌더링하는 일도 많아서요!

```ts
export const THUMBNAIL = {
  COFFEE: { src: coffeeImage, alt: '커피 쿠폰' },
  DRINK: { src: beerImage, alt: '술 쿠폰' },
  MEAL: { src: mealImage, alt: '식사 쿠폰' },
} as const;
```

2022-10-18 06:44 UTC, juunzzi commented on frontend/src/@components/coupon/CouponCreateForm/index.tsx
> +            </button>
오오 그럼 지프거 머지되면 리베이스 하고 적용해서 올릴게요!

2022-10-18 07:58 UTC, euijinkk requested changes
수고하셨습니다!! 
쿠폰 생성이 편하게 가능하겠네요!

아래와 같이 li의 list-style이 있어서, 제 PR에서 none으로 설정해두었습니다!
<img width="376" alt="image" src="https://user-images.githubusercontent.com/24906022/196370363-14d05001-804c-4415-80f6-0c628e870af3.png">

## tabIndex 사용 논의
a,button, input 요소가 아닌 것에 tabIndex를 다는 것에 대해 논의해봐야할 것 같은데요.

click, keyboard event가 필요없는 곳에 포커스가 가게되면, 좀 불편할 수 있을 것 같거든요.
비장애인 이용자는 확실히 불필요한 focus라고 느낄 것 같아요.

시각장애인은 어떻게 데스크톱을 이용하는지 좀 알아봐야 결정이 될것같긴한데요.
준찌는 어떤 의도로 했고, 필요하다고 생각하는지 궁금하네요!

2022-10-18 07:58 UTC, euijinkk commented on frontend/src/@components/@shared/SelectInput/index.tsx
> +      <Styled.SelectContainer tabIndex={0}>{children}</Styled.SelectContainer>
이 Container에 tabIndex를 주신 이유가 궁금해요! 
일반 이용자에게는 불편한 tabIndex인것같아요.
a, button, input 같은 요소 이외에 언제 tab이 가야하는가에 대한 기준을 논의해보면 좋을것같아요!

2022-10-18 07:58 UTC, euijinkk commented on frontend/src/@components/coupon/CouponCreateForm/index.tsx
> +import { ChangeEventHandler, FormEventHandler, KeyboardEvent, MouseEventHandler } from 'react';
KeyboardEvent 는 안쓰는것같네욤!~!

2022-10-18 07:58 UTC, euijinkk commented on frontend/src/@components/coupon/CouponCreateForm/index.tsx
>            </Styled.FeelOption>
voiceover가 #을 "숫자기호"라고 읽던데요! 저는 아래와 같이 aria-label을 달아주는건 보았는데, 어때요?

```suggestion
            <button type='button' aria-label={`hashtag ${couponTag}` onClick={onSelectCouponTag(hashtag)}>
              #{hashtag}
            </button>
          </Styled.FeelOption>
```

2022-10-18 07:58 UTC, euijinkk commented on frontend/src/@components/user/UserSearchForm/index.tsx
> +
누가 선택되었는지 알수가 없네요! 이름이 추가되면 좋을것 같고, 아래와 같이 심플하게 가는건 어때요?

```suggestion
        const ariaLabel = `${user.nickname} ${isSelected ? '선택' : '선택해제'}`
```

2022-10-18 07:59 UTC, euijinkk commented on frontend/src/@components/coupon/CouponCreateForm/index.tsx
> +            </button>
넵 좋습니다!

2022-10-18 09:07 UTC, juunzzi commented on frontend/src/@components/@shared/SelectInput/index.tsx
> +      <Styled.SelectContainer tabIndex={0}>{children}</Styled.SelectContainer>
왜 불편한 tabIndex 라고 생각하시나요 지프!!

2022-10-18 09:08 UTC, juunzzi commented on frontend/src/@components/coupon/CouponCreateForm/index.tsx
> +import { ChangeEventHandler, FormEventHandler, KeyboardEvent, MouseEventHandler } from 'react';
아 맞네요 ㅋㅋㅋ 버튼 없이 키보드 이벤트로 처리할려다 남은 잔재네요!! 제거하겠습니다!!!

2022-10-18 09:13 UTC, juunzzi commented on frontend/src/@components/user/UserSearchForm/index.tsx
> +
오 !!! 맞네요 직접들어보니깐 ㅋㅋㅋ 말이너무 길어서 짜증이 나는..? 느낌? 사용자들도 불편하다고 느낄 것 같아요!! 또 닉네임을 읽어주지 않으니 알 수가 없겠군요 !! 반영해두었습니다!

2022-10-18 09:32 UTC, euijinkk commented on frontend/src/@components/@shared/SelectInput/index.tsx
> +      <Styled.SelectContainer tabIndex={0}>{children}</Styled.SelectContainer>
가정은 <tab은 이벤트가 발생할 수 있는 곳으로 가야한다> 였습니다.
이벤트가 없는 곳에 tab이 가는 것이 의미가 있을까요?

아래에 이야기했지만, 시각장애인들에게는 이를 읽어준다는 장점이 있을수도 있지만, 시각 장애인이 tab으로 정보를 읽는 것 같진 않네요.
netflix, naver, 대한항공 등의 사례를 보아도 button, input, a 태그 이외에는 포커스가 가지 않네요.

2022-10-18 09:32 UTC, euijinkk commented on frontend/src/@components/user/UserSearchForm/index.tsx
> +
굿입니다!

2022-10-18 09:33 UTC, juunzzi commented on frontend/src/@components/@shared/SelectInput/index.tsx
> +      <Styled.SelectContainer tabIndex={0}>{children}</Styled.SelectContainer>
흠.. 어떤 사례인지는 모르겠으나.. 옵션으로 바로 포커싱이 넘어간다면 사용자는 하나의 인풋에 여러개의 옵션이 있는줄 알지않을까요 지프쿤?

2022-10-18 09:34 UTC, juunzzi commented on frontend/src/@components/@shared/SelectInput/index.tsx
> +      <Styled.SelectContainer tabIndex={0}>{children}</Styled.SelectContainer>
Container에 aria label을 달아둬야할 것 같긴하네요 ㅋㅋㅋ 그리고 일반 사용자로 하여금 왜 불편한지에 대해 물은것입니다!

2022-10-18 09:36 UTC, juunzzi commented on frontend/src/@components/@shared/SelectInput/index.tsx
> +      <Styled.SelectContainer tabIndex={0}>{children}</Styled.SelectContainer>
다시 한번 환기시키는 겸 말씀드리자면 저희한테 `SelectInputContainer`는 `Input` 입니다! 저희가 `select`를 확장해서 개발하는게 아닌 `div`로 `Input`을 흉내내는 형태의 `UI`입니다. 그렇기 때문에 이런 작업은 필요하다고 생각합니다! 뭐 input 태그인 셈이죠

2022-10-18 09:40 UTC, euijinkk commented on frontend/src/@components/@shared/SelectInput/index.tsx
> +      <Styled.SelectContainer tabIndex={0}>{children}</Styled.SelectContainer>
> 사용자는 하나의 인풋에 여러개의 옵션이 있는줄 알지않을까요

이게 무슨 의미인지 모르겠어요! 

> 일반 사용자로 하여금 왜 불편한지에 대해 물은것입니다!
이벤트가 발생하지 않는 곳에 불필요하게 tab이 가기때문에 불편하다는 것이었습니다.

준찌는 어떤 장점을 생각하고 tabIndex를 부여했는지 말해줄 수 있나요?

2022-10-18 10:02 UTC, merged