docs: 이슈 템플릿 종류 추가 및 세부 설정 수정
woowacourse-teams/2022-kkogkkog pull request #5
Opened 2022-07-02 04:51 UTC by bugoverdose

## 내용

- 디폴트 이슈 템플릿 추가
- 기존 BE/FE 이슈 템플릿 수정
  - 템플릿명(name) & 설명(about) 수정
  - 라벨(labels) 수정 
  - assignees 목록 수정
  - 파일명 수정
- 이슈 본문 수정 및 주석을 기반으로 설명 추가

## 리뷰어를 위한 사항

- 굳이 주말 내에 리뷰할 필요는 없는데, 평일 코어 타임 때 일일이 토론하기 애매한 내용이라고 생각해서 PR로 최종 결과물 만들어서 공유합니다. 
- 개선사항이나 기능에 대한 질문이 있으면 자유롭게 리뷰 남기면 될 것 같아요.  
- cf) develop에 머지하게 되면, 즉시 master로도 머지해야 할 것 같은데 다소 번거롭다는 생각이 드네요.

2022-07-02 05:04 UTC, bugoverdose reviewed
기능에 대한 세부 설명입니다.

P.S. 1이슈 1PR로 일일이 쪼개려고 했는데, 기능 구현이나 hotfix가 아니라 설정 관련 내용은 PR별로 쪼개는게 잘 안되네요.

2022-07-02 05:04 UTC, bugoverdose commented on .github/ISSUE_TEMPLATE/default_template.md
> +assignees: "bugoverdose, DWL21, euijinkk, Hyunta, juunzzi, Wishoon"
기본적으로 팀원 6명 전원이 일단 선택되고, 한명씩 제거하는게 덜 번거롭다고 생각해요.

2022-07-02 05:04 UTC, bugoverdose commented on .github/ISSUE_TEMPLATE/default_template.md
> +-->
노션에서 저희가 어떻게 작업하기로 논의한 내용들을 찾아보았는데 산재해있어서 찾기 힘들었어요. 주석에 기재해서 그때그때 읽는게 낫지 않나 싶어요.

2022-07-02 05:43 UTC, Wishoon commented on .github/ISSUE_TEMPLATE/backend_template.md
> +assignees: "bugoverdose, DWL21, Hyunta, Wishoon"
labels와 assignees 템플릿을 복사했었는데 오타가 있었군요 😅 수정 감사합니다 ㅎ

FE/BE 템플릿 구분은 이슈 등록 시 좀 더 편하게 하자는 취지에서 작성되었기 때문에 월요일 주간 회의 때 한번 의논해보는 것이 좋을 것 같네요.

2022-07-02 06:35 UTC, bugoverdose commented on .github/ISSUE_TEMPLATE/backend_template.md
> +assignees: "bugoverdose, DWL21, Hyunta, Wishoon"
@Wishoon 사실 오타 같은건 루키가 실수했다기보다는 몹 프로그래밍 자체의 한계 같아요. 당시에 전원이 화면 보고 있었는데 못 찾았으니까요. 

PR을 통해 작업물을 서로 리뷰하는 과정이 필요하다는 생각이 드네요.

2022-07-02 06:44 UTC, bugoverdose commented on .github/ISSUE_TEMPLATE/backend_template.md
> +assignees: "bugoverdose, DWL21, Hyunta, Wishoon"
+ 아 템플릿 구분에 대한 생각은 그냥 이슈 템플릿에 대한 제 전반적인 생각인거고, 사실 개발 단계에서는 어차피 저희만 이슈를 만들테니 지금처럼 BE/FE로 구분하는게 편리하다는 점에 대해 저도 동의해요.

2022-07-04 06:27 UTC, Hyunta requested changes
주말동안 오타도 수정하고 고생하셨습니다!
30분컷이긴 했지만, 그래도 신경써준 부분 감사합니다

2022-07-04 06:27 UTC, Hyunta commented on .github/ISSUE_TEMPLATE/backend_template.md
> +해당 작업의 필요성 및 전반적인 개요
배경을 조금 구체적으로 레오가 말한 것 처럼
As-is, To-be로 변경하면 좋을 것 같습니다

```suggestion
## as-is
현상황에서의 문제점

## to-be
변경해야하는 이유 혹은 목표
```

2022-07-04 06:27 UTC, Hyunta commented on .github/ISSUE_TEMPLATE/backend_template.md
> +-->
공유사항을 안쓰게 되는 상황들이 훨씬 많을 것 같아요.
항상 없음으로 쓰기 귀찮을 것 같아서 삭제하는게 어떨까요?

2022-07-09 07:29 UTC, bugoverdose commented on .github/ISSUE_TEMPLATE/backend_template.md
> +해당 작업의 필요성 및 전반적인 개요
이미 배경과 진행사항이 각각 as-is와 to-be에 대응된다고 생각합니다.

2022-07-09 07:45 UTC, bugoverdose commented on .github/ISSUE_TEMPLATE/backend_template.md
> +-->
이슈에서는 주석화하고, PR 템플릿에 추가했습니다.

2022-07-10 14:24 UTC, Hyunta approved these changes
고생하셨습니다 정!
approve 할게요

2022-07-11 09:07 UTC, merged